### ISSUE TITLE
Can I get a ca certificate file?

### ISSUE THREAD

**Issue by sksk6969** [krlvm/PowerTunnel-Android#62] opened 2021-03-12 02:25 UTC
I can't install the certificate on Android 11, so it tells me to install it directly from the settings.

**Comment by krlvm** [comment] 2021-03-12 04:10
Certificate generates dynamically on the first run, so I can't send you the file. Looks like duplicate of #53 - extracting the certificate for manual installation will be available in an upcoming version. 

If you have root access, you can navigate to the data directory of the app and find it there. 

Why you can't install it from the app?

**Comment by Twilite** [comment] 2021-04-06 21:22
FYI: https://stackoverflow.com/questions/61386312/cant-install-ca-certificate-on-android-11#62465897

> Apps installed on unmanaged devices or in a device's personal profile can no longer install CA certificates using createInstallIntent(). Instead, users must manually install CA certificates in Settings.

Tried to install in app, returning following message: 
![screenshot](https://user-images.githubusercontent.com/44067436/113779786-cf916900-9760-11eb-9b00-ebeba27a6e9f.jpg)

Seems like manual install would be the only viable solution on Android 11.

**Comment by krlvm** [comment] 2021-04-07 15:24
I will add an option that allows exporting a certificate within a week or two

**Closed** 2021-04-16 21:39 UTC
Labels: bug, enhancement
