### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by ez2dj** [krlvm/PowerTunnel-Android#91] opened 2021-11-10 04:31 UTC
![Screenshot_20211110-133021_PowerTunnel](https://user-images.githubusercontent.com/53131830/141050079-381e603e-926e-47e9-9fd9-d559555c2295.jpg)

**Comment by krlvm** [comment] 2021-11-10 09:54
Thanks for reporting this, it will be fixed in an upcoming stable version 2.0.
If this crash prevents you from using the app, you can switch to the [latest stable version 1.9.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1) until the v2.0 is released.

**Comment by krlvm** [comment] 2021-11-10 09:54
Duplicate of #87

**Closed** 2021-11-10 09:54 UTC
Labels: bug
