### ISSUE TITLE
Doesn't work on A11

### ISSUE THREAD

**Issue by ghost** [krlvm/PowerTunnel-Android#82] opened 2021-09-01 05:22 UTC
App Version: 2.0-rc3/rc4
Device: Redmi Note 8 (ginkgo)
ROM: crDroid A11

The pre-release versions do not work on A11. I have tried using the default DoT & DoH servers as well as custom dns servers. I also tried disabling chunking mode and enabling SNI Spoil (installed the certificate).

I'm currently using the latest stable release. The default DoT servers work great, but custom dns & the default DoH servers don't work.

Please let me know if there is any additional information I can provide you with.

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7091465/powertunnel.log.txt)
[powertunnel.log (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/7091466/powertunnel.log.1.txt)

**Comment by user6660** [comment] 2021-09-01 15:25
With the latest pre-release versions, I tried using the default Google & Cloudflare DoT & DoH. I even tried manually entering the dns hostnames in the custom field. Didn't work. It says connected, but in chrome I get ERR_CONNECTION_TIMEOUT or TOOK TOO LONG TO RESPOND & none of my apps work.

**Comment by user6660** [comment] 2021-09-01 15:58
With the latest pre-release versions, I tried using the default Google & Cloudflare DoT & DoH. I even tried manually entering the dns hostnames in the custom field. Didn't work. It says connected, but in chrome I get ERR_CONNECTION_TIMEOUT or TOOK TOO LONG TO RESPOND & none of my apps work.

**Comment by krlvm** [comment] 2021-09-01 17:22
Can't reproduce the issue, make sure you follow this pattern:
- DoH: start the address with `https://`, e.g. `https://8.8.8.8/dns-query` or `https://dns.google/dns-query`
- DNS: write IP address, e.g. `8.8.8.8`

**Comment by user6660** [comment] 2021-09-01 17:40
I'll try that again... But, shouldn't the default dns providers work when selected?

**Comment by krlvm** [comment] 2021-09-01 18:15
The pre-installed DNS providers should work: you can test them [here](https://www.nnov.kp.ru/media/849174/)

**Comment by user6660** [comment] 2021-09-01 18:58
Tried with the latest hotfix build & my device still can't connect. I'm not sure if these logs are of any help.

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7093666/powertunnel.log.txt)
[2021-09-02-00-19-59.log](https://github.com/krlvm/PowerTunnel-Android/files/7093669/2021-09-02-00-19-59.log)

**Comment by krlvm** [comment] 2021-09-01 19:14
The crash you reported is not related to this issue, are you trying to connect to a blocked website or DNS just does not work?
There's no errors in your logs, but I recently changed DNS Resolving logic, can you try [v2.0-rc2](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0-rc2)?
It also may be a bug in your firmware (as I understand it, you are using a custom ROM), try using Proxy mode without VPN.
What exactly did you write the DNS address?

**Comment by user6660** [comment] 2021-09-02 05:49
﻿The pre-release versions just won't work. What's strange is, if there's an issue with the firmware, then the stable version shouldn't work too, but it does.

Hopefully this recording explains it better...

https://user-images.githubusercontent.com/89892692/131788679-85a9c47c-c763-49ac-a617-265029dafef6.mp4

**Comment by krlvm** [comment] 2021-09-02 12:12
There might be a problem with the VPN Interceptor, try this build:
[PowerTunnel-99dns.zip](https://github.com/krlvm/PowerTunnel-Android/files/7098671/PowerTunnel-99dns.zip)

**Comment by krlvm** [comment] 2021-09-02 12:34
There might be a problem with the VPN Interceptor, try this build:
[PowerTunnel-99dns2.zip](https://github.com/krlvm/PowerTunnel-Android/files/7098884/PowerTunnel-99dns2.zip)

**Comment by user6660** [comment] 2021-09-02 17:20
Still doesn't work i'm afraid...

**Comment by krlvm** [comment] 2021-09-02 19:05
Go to plugin manager, uninstall DNS plugin and install this version (extract .jar from .zip first), which prints debug messages:
[DNSResolver-Android.zip](https://github.com/krlvm/PowerTunnel-Android/files/7101151/DNSResolver-Android.zip)

**Comment by user6660** [comment] 2021-09-03 05:13
[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7103446/powertunnel.log.txt)

**Comment by krlvm** [comment] 2021-09-03 11:46
```
09-03 10:38:14.978 12450 19318 I DNSPlugin: Plugin is supported by your OS (Java >= 8)
09-03 10:38:14.979 12450 19318 I DNSPlugin: Preset: CUSTOM
09-03 10:38:14.979 12450 19318 I DNSPlugin: DNS Address:  ; ... <-----
```

Looks like you entered an empty DNS address

**Comment by user6660** [comment] 2021-09-03 12:35
In that same log, you'll find I attempted to also use Cloudflare & Google. Here's another log.

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7105848/powertunnel.log.txt)

Just to clarify - If the dns address field is left blank, shouldn't my isp's dns be used as default?

**Comment by krlvm** [comment] 2021-09-03 12:58
Yes, if the field is empty, your ISP DNS will be used.

`one.one.one.one` will not work because it is URL while you trying to use it as regular DNS server - you need to use either `1.1.1.1` for plain DNS, either `https://1.1.1.1/dns-query` for DoH

**Comment by user6660** [comment] 2021-09-03 13:35
> ```
> 09-03 10:38:14.978 12450 19318 I DNSPlugin: Plugin is supported by your OS (Java >= 8)
> 09-03 10:38:14.979 12450 19318 I DNSPlugin: Preset: CUSTOM
> 09-03 10:38:14.979 12450 19318 I DNSPlugin: DNS Address:  ; ... <-----
> ```
> 
> Looks like you entered an empty DNS address

This was with the dns field empty...

**Comment by user6660** [comment] 2021-09-03 13:38
> Yes, if the field is empty, your ISP DNS will be used.
> 
> `one.one.one.one` will not work because it is URL while you trying to use it as regular DNS server - you need to use either `1.1.1.1` for plain DNS, either `https://1.1.1.1/dns-query` for DoH

This log is with, `1.1.1.1` & `https://1.1.1.1/dns-query`.
[Uploading powertunnel.log.txt…]()

**Comment by krlvm** [comment] 2021-09-03 13:42
Did you try to open any website in that session? I see that no request to the proxy server went through, most likely the problem is with the VPN Interceptor.

**Comment by user6660** [comment] 2021-09-03 14:17
Yes... In the below log, you'll see I tried connecting to dnsleaktest.com among other websites.

https://github.com/krlvm/PowerTunnel-Android/files/7103446/powertunnel.log.txt

**Comment by krlvm** [comment] 2021-09-03 15:50
After re-reading the latest log I'm sure it is a problem with VPN Interceptor, try to open an address that does not need DNS Resolving (e.g. https://1.1.1.1 - it is already resolved) in web browser: if the problem is not related to DNS, it will fail to load.

**Comment by user6660** [comment] 2021-09-03 16:24
You're right... I set the custom dns to 1.1.1.1 & opened https://1.1.1.1 in chrome & it did not load.

**Comment by krlvm** [comment] 2021-09-03 16:35
Can you try to load `https://1.1.1.1` without the custom DNS server?

**Comment by user6660** [comment] 2021-09-03 16:41
I did, yes... & it failed to load.

**Comment by krlvm** [comment] 2021-09-03 16:56
Thank you very much for the detailed information, the only change in the VPN Interceptor logic since version 1.9.1 is that now the proxy server receives the hostname instead of the IP address (#73), in order to exclude that the problem is related to the proxy server, you can put the application in Proxy mode (after that, you need to configure it in the WiFi or mobile network settings) and check if the problem is fixed.

This build has the old VPN behaviour restored:
[PowerTunnel-99u5.zip](https://github.com/krlvm/PowerTunnel-Android/files/7107436/PowerTunnel-99u5.zip)

**Comment by user6660** [comment] 2021-09-03 17:20
Using the app in proxy mode is what I'd like to avoid... Setting up each app to use proxy is too cumbersome.

I really hope this can be fixed.

**Comment by krlvm** [comment] 2021-09-03 17:29
Attached build doesn't work?

**Comment by user6660** [comment] 2021-09-03 17:36
I'll try it in some time... In class right now, sorry.

**Comment by user6660** [comment] 2021-09-03 18:38
@krlvm No, it doesn't work...

**Comment by krlvm** [comment] 2021-09-03 19:15
This is really strange, I've tested it on five devices from different vendors and with different Android versions and can't reproduce, I've built a version with extended debugging including debug messages from VPN Interceptor: 
[PowerTunnel-99dbg.zip](https://github.com/krlvm/PowerTunnel-Android/files/7108064/PowerTunnel-99dbg.zip)

I'd suggest to clear application data and disable all plugins to test it

**Comment by user6660** [comment] 2021-09-04 04:46
The build you provided with the old VPN behaviour still had version 1 preview 4 dns plugin. Which is why, I guess, didn't work.

Here are logs from the version with extended debugging. I cleared all app data & disabled plugins before collecting the logs.

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7109204/powertunnel.log.txt)

**Comment by krlvm** [comment] 2021-09-04 10:14
The problem seems to be not in the DNS, but in the VPN and proxy connection.
The logs show that the requests are correctly reaching the proxy server, but for some reason there is no response.

Please, switch to Proxy mode temporary to eliminate the possibility of a problem on the proxy server side. Since you are using Bromite it's very easy, open Settings -> Privacy -> Proxy Configuration, set "single proxy" to `PROXY 127.0.0.1` and tap "Apply". Then you can easily disable it by clicking "Clear", so it shouldn't cause much inconvenience.

![photo_2021-09-04_13-01-08](https://user-images.githubusercontent.com/51774833/132090970-6ce8ba3b-1ede-49be-b970-78906442a717.jpg)

This build has additional debug messages which should help to diagnose the root problem. You can try with DNS Plugin off and on. Sorry for the inconvenience.
[PowerTunnel-99proxydbg.zip](https://github.com/krlvm/PowerTunnel-Android/files/7109581/PowerTunnel-99proxydbg.zip)

**Comment by user6660** [comment] 2021-09-04 10:24
Thank you.

I'll stick to version 1.9.1 for now.

**Comment by krlvm** [comment] 2021-09-04 10:29
Ok, let me know when you test the new version.

**Comment by user6660** [comment] 2021-09-04 10:44
Sure... Here's the log

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7109615/powertunnel.log.txt)

**Comment by krlvm** [comment] 2021-09-04 11:07
Did you manage to open a website this time, or were you still getting the timeout error? It also looks like you ran it in VPN mode.

**Comment by user6660** [comment] 2021-09-04 11:26
Hi! I am terribly sorry... Yes, that was in vpn mode.
This is using proxy mode & I set single proxy to PROXY 127.0.0.1:8085 in bromite. Websites still wont open.

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7109675/powertunnel.log.txt)

**Comment by krlvm** [comment] 2021-09-04 11:56
Thanks for the log, looks like responses doesn't come to the proxy server, it may be related to the way proxy handles HTTPS packets.

Are plain-HTTP websites like http://13.32.23.27/ or http://neverssl.com loading in any mode?

**Comment by user6660** [comment] 2021-09-04 12:13
No, those plain-HTTP websites don't open.

[powertunnel.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7109718/powertunnel.log.txt) - Proxy mode log

[powertunnel.log (1).txt](https://github.com/krlvm/PowerTunnel-Android/files/7109723/powertunnel.log.1.txt) - vpn mode log

**Comment by krlvm** [comment] 2021-09-04 14:32
Thank you, it is now clear that this is not a DNS problem:
`DnsLogger: onResolutionRequest(github.com -> 13.234.210.38)`
`DnsLogger: onResolutionRequest(neverssl.com -> 205.251.253.205)`

~~However, no responses come, while the VPN/Proxy behaviour hasn't changed since v1.9.1. There's also may be some connectivity bugs in the build i sent because it comes from the active development branch, try reinstalling [the latest stable preview version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0-rc4).~~

~~Do you use any firewall or network monitoring tool?~~

I just fixed a similar bug and noticed that the behavior of the proxy server is exactly the same: it receives requests, but does not send responses, when you tried to open http://neverssl.com you had an error handled by the browser (as in the screenshot) , or you saw some kind of text error (text in the upper left corner, for example "Bad Gateway" or "Bad Host").

![1](https://user-images.githubusercontent.com/51774833/132098019-b19ff5eb-ac0a-4bf4-bb80-8a7e173c1f32.png)

I recall that I was getting the same problem as yours when I was developing the first version of the application over a year ago.

**Comment by user6660** [comment] 2021-09-04 14:41
The error was, "ERR_TIMED_OUT".

There was no text error in the upper left corner.

**Closed** 2021-12-07 14:09 UTC

**Comment by yusatia** [comment] 2022-01-09 08:12
I don't know if it's a related issue, however, on my Huawei SNE-LX1 (A10) device, this app works perfectly, however on my Samsung A705FN (A11) device, it doesn't work at all. I've tried different combinations of LibertyTunnel settings and I've had no luck at all with them.

[new.log.txt](https://github.com/krlvm/PowerTunnel-Android/files/7834668/new.log.txt)

Here's my log file.

**Comment by krlvm** [comment] 2022-01-09 13:34
So you can connect to unblocked sites with PowerTunnel on your Android 11 device?
Can you try [version 1.9.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1)?

**Comment by yusatia** [comment] 2022-01-09 14:35
Precisely. Sadly, it doesn't work with version 1.9.1, and to note as an extra, while 1.9.1 was turned on, my WhatsApp didn't work, however, websites like Google did.

**Comment by krlvm** [comment] 2022-01-09 15:28
Are you using the same ISP on both devices?

**Comment by yusatia** [comment] 2022-01-09 15:29
Yeah. They both are connected to my house Wi-Fi.

**Comment by krlvm** [comment] 2022-01-09 16:41
Can't reproduce on Android 11+ devices. If you can still access unblocked websites when PowerTunnel is running, that means that proxy server is working correctly, do you have any other active application which monitors network activity installed on your device?
