### ISSUE TITLE
Feature Request : F-Droid Repo

### ISSUE THREAD

**Issue by Chidhambararajan** [krlvm/PowerTunnel-Android#56] opened 2021-01-24 04:51 UTC
I understand that the app cannot be published in Google Play , can you guys try out F-Droid?

**Comment by krlvm** [comment] 2021-01-24 07:31
It can't be published to F-Droid now because of the .jar library used in build, but I think it can be fixed in an upcoming release.
Duplicate of #19.

**Closed by krlvm** 2021-01-24 07:31 UTC
