### ISSUE TITLE
DNS doesn't work with the latest Android versions

### ISSUE THREAD

**Issue by jemblink21** [krlvm/PowerTunnel-Android#6] opened 2020-04-03 17:44 UTC
override dns serves not working on Android 10. I try all server, nothing works.

**Comment by krlvm** [comment] 2020-04-03 17:46
I know about this problem since version 1.1.

**Comment by krlvm** [comment] 2020-04-03 18:02
I can't reproduce this issue, seems it has been fixed in the [latest](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.3) release (v1.3). Are you using the latest version?
You can check does DoH work on [this](https://ipleak.net/) website.

**Comment by jemblink21** [comment] 2020-04-04 00:28
Yes. I'm using 1.3 version. 
My device is Xiaomi mi a2 android one
When used dns provider, can't access internet anymore
![Screenshot_20200404-072521](https://user-images.githubusercontent.com/57548817/78414300-b33a8800-7645-11ea-8239-dc60cb7f083d.png)

**Comment by krlvm** [comment] 2020-04-04 10:16
Tried on multiple Android 10 devices, still can not reproduce the issue, can you send logcat?
For Windows: `adb shell "logcat --pid=$(pidof -s <package_name>)"`
For Linux/macOS: `adb shell 'logcat --pid=$(pidof -s <package_name>)'`

**Comment by krlvm** [comment] 2020-04-04 11:22
I've made a version that collects errors.
Reproduce the issue and open "Show errors" in three-dots menu. After you grant permission, `PowerTunnelLogs.txt` will be saved and you will be able to access it using your file manager.
Please, upload that file.
[PowerTunnel-err.zip](https://github.com/krlvm/PowerTunnel-Android/files/4431223/PowerTunnel-err.zip)

**Comment by krlvm** [comment] 2020-04-10 10:38
I've tested the app again on several devices of different vendors and still can't reproduce the issue.
It is possible that the DNS servers are blocked in your country or your provider is blocking packets related to DNS.
Reopen this issue if you're sure that it should work.

**Closed by krlvm** 2020-04-10 10:38 UTC
Labels: bug

**Comment by DRSDavidSoft** [comment] 2020-12-18 20:28
Can you please add the option to display logcats inside the app's settings?

It seems that the DoH providers aren't working on my device, I'd like to help debug this issue.

**Comment by krlvm** [comment] 2020-12-18 20:33
> PowerTunnel-err.zip

IIRC, this version supplied with all that is needed to debug this (use three-dots menu), nothing has been changed in DNS logic over this time.
