### ISSUE TITLE
Its not connecting in vpn mode

### ISSUE THREAD

**Issue by olva90** [krlvm/PowerTunnel-Android#100] opened 2021-12-29 14:58 UTC
Power tunnel is not working in my xiaomi redmi note 4x (android 7). After clicking the connect option in the app it immediately try to connect the vpn mode by showing green from red but few seconds later it become red again and not connecting to vpn. Also want to mention that i didn't change any option in the app, just install and click the connect option. Is that a bug?

**Comment by krlvm** [comment] 2021-12-29 16:19
Will the [previous version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1) work?

**Comment by olva90** [comment] 2021-12-29 19:01
I just tried 1.9.1 and its working

**Comment by PhoenixCODE2322** [comment] 2022-01-19 00:19
> Will the [previous version](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v1.9.1) work?

it's happening on my device too.. currently using 1.9.1..

Please tell us how can we assist you in resolving this bug.. i can test and send logs if there is a way .. i am on rooted device

**Comment by krlvm** [comment] 2022-01-19 11:49
Thanks for your willingness to help.

A small digression for context:
I've rewrote the entire PowerTunnel foundation in version 2.0 release, including proxy server and Android VPN Service management stack, which resulted in breaking network connection on some Android devices when PowerTunnel is working (so I don't even push version 2.0 to more users). This could came either from a bug in proxy server implementation, either from a bug from the basic VPN Service DNS resolving (however, all works flawlessly on all my devices, including Android 5, 6, 7, 8, 9 and 10 devices).
Related issue: #82 

It was not clear from your post if everything works with version 1.9.1? Are you able to connect to the blocked sites on version 2.0 or the Internet connection does not work at all after connecting to PowerTunnel VPN?
What firmware and Android version are you using?

To identify the problematic component in the circuit, try to test version 2.0 in proxy server mode, to do this, go to the settings and switch the VPN to proxy mode. After that, try setting "127.0.0.1:8085" as a proxy server in your WiFi settings if you are connected via WiFi, or using a browser that supports setting a proxy server, such as Bromite ([screenshot](https://github.com/krlvm/PowerTunnel-Android/issues/82#issuecomment-912947766)) or Firefox (using FoxyProxy extension, proxy type is HTTPS/SSL). If you cannot establish a connection, then the problem is definitely in the proxy server.

**Comment by PhoenixCODE2322** [comment] 2022-01-19 12:25
Ok here you go .. Tested all the things you mentioned ..

CustomRom-S-Tempest-UNOFFICIAL-RMX1851-20211230
December 5, 2021 Security Patch
Android 12

Power Tunnel 1.9.1 -- Using at default config with VPN mode .. everything works perfectly..Blocked sites are accessible.

Powert Tunnel 2.0-- Default config
VPN Mode-- Youtube and instagram App working but speed is slow as comoared to 1.9.1 , but browser are not working.. Bromite and OH browser..( Web surfing is not avilable)
Blocked sites are also not working

Proxy Mode- Went to proxy in bromite and changed there to custom proxy like you said .. Blocked sites are working..
Apps are working..

OH Browser-- it does not has proxy settings ... so blocked sites are not working here but normal web surfing is available.

**Comment by krlvm** [comment] 2022-01-19 13:10
Thank you very much for detailed response.

While I'm thinking what can be the root problem, I remembered that the one change I did to the VPN stack was #73.
Please, try this build: [PowerTunnel-100-RH.zip](https://github.com/krlvm/PowerTunnel-Android/files/7897312/PowerTunnel-100-RH.zip)

**Comment by krlvm** [comment] 2022-01-19 13:37
Thanks a lot for your help!
I will release a version with fix soon.

**Comment by PhoenixCODE2322** [comment] 2022-01-19 13:41
✌️.. Thanks for this great app ... android and windows... both are awesome ..love this project...

**Closed** 2022-01-19 15:47 UTC
Labels: bug

**Comment by krlvm** [comment] 2022-01-19 16:50
Fix is available in [version 2.0.1](https://github.com/krlvm/PowerTunnel-Android/releases/tag/v2.0.1), you need to enable option named "Resolve domain names" in VPN category of settings. Please, check if it works for you.

**Comment by PhoenixCODE2322** [comment] 2022-01-19 21:13
Thanks for the Quick Fix.. It works now.. AdBlock Plugin - it's ok ... you can take your time there .... Thanks again

**Comment by krlvm** [comment] 2022-01-25 19:35
@PhoenixCODE2322, I think I've managed to find the root case of the problem and looks like it's completely fixed in development branch even without additional hacky options, can you confirm?

[PowerTunnel-v2.1-dev.zip](https://github.com/krlvm/PowerTunnel-Android/files/7936628/PowerTunnel-v2.1-dev.zip)

**Comment by PhoenixCODE2322** [comment] 2022-01-25 19:40
> @PhoenixCODE2322, I think I've managed to find the root case of the problem and looks like it's completely fixed in development branch even without additional hacky options, can you confirm?
> 
> [PowerTunnel-v2.1-dev.zip](https://github.com/krlvm/PowerTunnel-Android/files/7936628/PowerTunnel-v2.1-dev.zip)

ok will test it now, can you tell me which specific things i need to test ?

**Comment by krlvm** [comment] 2022-01-25 19:43
Thank you, if the issue is fixed, all should work fine without modifying any configuration.

**Comment by PhoenixCODE2322** [comment] 2022-01-25 19:43
reporting- 

1) VPN mode, default config ..... everything works
2) VPN mode, adblock plugin on , everything else default ---- working perfectly

**Comment by PhoenixCODE2322** [comment] 2022-01-25 19:45
Thanks for the fix.. great work 👍

**Comment by krlvm** [comment] 2022-01-25 19:47
Thanks for confirming, now the hostnames are always extracted properly, so it is also possible to use government blacklists and AdBlock plugin without stability issues.
