### ISSUE TITLE
Incompatibility with the Samsung August patch

### ISSUE THREAD

**Issue by SleepyRabbitXVI** [krlvm/PowerTunnel-Android#29] opened 2020-09-10 08:36 UTC
Hi, the app keeps crashing after I installed the latest [software update ](https://doc.samsungmobile.com/SM-A505F/INS/doc.html) on my galaxy A50. Used to work without any issues before. Tried re installing, still the same issue.

**Comment by krlvm** [comment] 2020-09-10 13:08
I have updated my Samsung phone yesterday and all is fine.
Could you share `adb logcat`?
Thanks in advance.

**Comment by SleepyRabbitXVI** [comment] 2020-09-10 18:27
OK so I had no idea what `adb logcat` was (I'm not a developer) and after pondering on the internet to learn about it, the command not working on my Windows 7 so upgrading to Windows 10, I finally was able to get the logcat and have attached the logcat.txt file which I hope is what you asked for. 
Guess I learned something new today haha. Thanks for the help!
[logcat.txt](https://github.com/krlvm/PowerTunnel-Android/files/5203907/logcat.txt)

**Comment by krlvm** [comment] 2020-09-10 19:31
The error throws because the latest security update requested a new permission to start VPN (why?):
`Neither user 10229 nor current process has **android.permission.INTERACT_ACROSS_USERS**`

I will push the fix within a 30 minutes!

Thank you!

**Comment by krlvm** [comment] 2020-09-10 20:51
After some searching, I figured out that it is a rare bug of a small amount of vendors, it should be fixed with the next software upgrade.

Do you have Samsung Secured Folder enabled?

I removed some stuff that could trigger the bug, this APK should work:
[PowerTunnel-v1.7.1-test.zip](https://github.com/krlvm/PowerTunnel-Android/files/5204584/PowerTunnel-v1.7.1-test.zip)
[Commit 2b0d5bca6b167b701ded38bcee552e16fd6bdf99](https://github.com/krlvm/PowerTunnel-Android/commit/2b0d5bca6b167b701ded38bcee552e16fd6bdf99)

**Comment by SleepyRabbitXVI** [comment] 2020-09-10 21:09
I don't have secure folder enabled, does having it enabled help? 

The new APK doesn't crash now but I can't load any webpages while it's running.

**Comment by krlvm** [comment] 2020-09-10 21:18
> I don't have secure folder enabled, does having it enabled help?

No, it could be the cause of the problem (now we know it does not)

Check your PowerTunnel settings if the webpages can't load, and if you can't load even the government resources, please, upload a new logcat.

**Comment by SleepyRabbitXVI** [comment] 2020-09-11 07:47
I was thinking if I should just grant the permission to the app using  `adb shell pm grant ru.krlvm.powertunnel.android android.permission.INTERACT_ACROSS_USERS` I feel like this should fix the crash issue.

**Comment by krlvm** [comment] 2020-09-11 11:00
This permission is available only for system apps, so it can't be granted without root.
The crash output is belongs to AndroidRuntime, so there is no way to filter the log I think

**Comment by SleepyRabbitXVI** [comment] 2020-09-11 11:16
> Do you see the VPN key icon in the notification bar?

I see the vpn key next to the wifi symbol but there used to be a notification before as well from where I could disconnect from the notification bar, I don't see that now. 

The settings are default which I used to use before and the webpages would load but now they don't with the same settings.

> The crash output is belongs to AndroidRuntime, so there is no way to filter the log I think.

What command should I use then because `adb logcat` keeps running infinitely.

**Comment by krlvm** [comment] 2020-09-11 11:19
You can use `adb logcat > output.txt` and then run PowerTunnel, after you've done, click Ctrl+C, the output will be saved in `output.txt`.

**Comment by SleepyRabbitXVI** [comment] 2020-09-11 13:14
Here you go. Ran powertunnel at 18:34
[output.txt](https://github.com/krlvm/PowerTunnel-Android/files/5209180/output.txt)

**Comment by krlvm** [comment] 2020-09-11 13:30
I see the cause of the crash is still the lack of the permission, but you said that the app is no longer crashes previously.

I will write a bug-report to Samsung, in the meantime you can configure PowerTunnel using proxy mode: enable "proxy mode" in PowerTunnel settings, and set the system proxy in WiFi settings if you're on WiFi, or on APN if you're using mobile connection, the default local proxy address is `127.0.0.1:8085`.

**Comment by SleepyRabbitXVI** [comment] 2020-09-11 13:36
Cool no worries. Let me know when it's fixed. 
Thanks for the help!
Cheers

**Comment by krlvm** [comment] 2020-09-11 21:20
I contacted the Samsung support, they admit the problem in the August patch and should release the fix with an upcoming September/October patch.

**Comment by SleepyRabbitXVI** [comment] 2020-09-12 06:23
Oh great. Thanks!

**Comment by krlvm** [comment] 2020-09-12 11:22
**PSA:** Samsung told the issue is related to Dual Messenger feature, disabling it can resolve the issue before you've received the September patch.

**Comment by SleepyRabbitXVI** [comment] 2020-09-12 11:45
Unable to disable dual messenger but uninstalled the apps using dual messenger. Powertunnel still crashes.

**Comment by krlvm** [comment] 2020-09-29 12:59
I see Samsung released an update for your device, can you check it?

**Comment by SleepyRabbitXVI** [comment] 2020-09-29 14:15
Yeah there was a small update few days ago but it didn't fix the problem.

**Comment by SleepyRabbitXVI** [comment] 2020-10-26 06:16
Alright so got the october patch a few days ago but the issue wasn't fixed

**Comment by krlvm** [comment] 2020-10-26 09:52
Do other VPN apps crash when you are trying to connect?

**Comment by SleepyRabbitXVI** [comment] 2020-10-26 09:53
I've got proton vpn which doesn't crash

**Comment by krlvm** [comment] 2020-11-12 00:00
Folks say this works with attached APK (v1.8.2-bootfix13-sam):
`adb shell pm grant ru.krlvm.powertunnel.android android.permission.INTERACT_ACROSS_USERS`

[PowerTunnel-v1.8.2-bootfix13-sam.zip](https://github.com/krlvm/PowerTunnel-Android/files/5527447/PowerTunnel-v1.8.2-bootfix13-sam.zip)

**Comment by SleepyRabbitXVI** [comment] 2020-11-12 05:15
Yup works now

**Comment by krlvm** [comment] 2020-11-12 05:19
> Yup works now, thanks!

Thanks for the help!

**Closed** 2020-11-12 06:20 UTC
Labels: not a bug
